env: dev
app_project: gosoline
app_family: get-started
app_group: grp
app_name: hello-world

// highlight-start
log:
    level: info
    handlers:
        main:
            type: iowriter
            channels:
                metrics:
                    level: error
                formatter:
                    level: error
            formatter: console
            level: info
            timestamp_format: 15:04:05.000
            writer: stdout
// highlight-end
