// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

// Topic is an autogenerated mock type for the Topic type
type Topic struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, msg
func (_m *Topic) Publish(ctx context.Context, msg *string) error {
	ret := _m.Called(ctx, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *string) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
