app:
  env: dev
  name: consumer
  tags:
    project: gosoline
    family: how-to
    group: grp

stream:
  input:
    consumer:
      type: sqs
      target_queue_id: events

  output:
    todos:
      type:
        type: sqs
        queue_id: todos
