// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import raven "github.com/getsentry/raven-go"

// Sentry is an autogenerated mock type for the Sentry type
type Sentry struct {
	mock.Mock
}

// Capture provides a mock function with given fields: packet, captureTags
func (_m *Sentry) Capture(packet *raven.Packet, captureTags map[string]string) (string, chan error) {
	ret := _m.Called(packet, captureTags)

	var r0 string
	if rf, ok := ret.Get(0).(func(*raven.Packet, map[string]string) string); ok {
		r0 = rf(packet, captureTags)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 chan error
	if rf, ok := ret.Get(1).(func(*raven.Packet, map[string]string) chan error); ok {
		r1 = rf(packet, captureTags)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(chan error)
		}
	}

	return r0, r1
}
