// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

// FileRecorder is an autogenerated mock type for the FileRecorder type
type FileRecorder struct {
	mock.Mock
}

// DeleteRecordedFiles provides a mock function with given fields: ctx
func (_m *FileRecorder) DeleteRecordedFiles(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecordFile provides a mock function with given fields: bucket, key
func (_m *FileRecorder) RecordFile(bucket string, key string) {
	_m.Called(bucket, key)
}

// RenameRecordedFiles provides a mock function with given fields: ctx, newPrefix
func (_m *FileRecorder) RenameRecordedFiles(ctx context.Context, newPrefix string) error {
	ret := _m.Called(ctx, newPrefix)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, newPrefix)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
