// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MutableResourceAware is an autogenerated mock type for the MutableResourceAware type
type MutableResourceAware struct {
	mock.Mock
}

type MutableResourceAware_Expecter struct {
	mock *mock.Mock
}

func (_m *MutableResourceAware) EXPECT() *MutableResourceAware_Expecter {
	return &MutableResourceAware_Expecter{mock: &_m.Mock}
}

// MutableResourceIds provides a mock function with no fields
func (_m *MutableResourceAware) MutableResourceIds() ([]string, bool) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MutableResourceIds")
	}

	var r0 []string
	var r1 bool
	if rf, ok := ret.Get(0).(func() ([]string, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MutableResourceAware_MutableResourceIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MutableResourceIds'
type MutableResourceAware_MutableResourceIds_Call struct {
	*mock.Call
}

// MutableResourceIds is a helper method to define mock.On call
func (_e *MutableResourceAware_Expecter) MutableResourceIds() *MutableResourceAware_MutableResourceIds_Call {
	return &MutableResourceAware_MutableResourceIds_Call{Call: _e.mock.On("MutableResourceIds")}
}

func (_c *MutableResourceAware_MutableResourceIds_Call) Run(run func()) *MutableResourceAware_MutableResourceIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MutableResourceAware_MutableResourceIds_Call) Return(_a0 []string, _a1 bool) *MutableResourceAware_MutableResourceIds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MutableResourceAware_MutableResourceIds_Call) RunAndReturn(run func() ([]string, bool)) *MutableResourceAware_MutableResourceIds_Call {
	_c.Call.Return(run)
	return _c
}

// NewMutableResourceAware creates a new instance of MutableResourceAware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMutableResourceAware(t interface {
	mock.TestingT
	Cleanup(func())
}) *MutableResourceAware {
	mock := &MutableResourceAware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
