// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	db_repo "github.com/justtrackio/gosoline/pkg/db-repo"
	crud "github.com/justtrackio/gosoline/pkg/httpserver/crud"

	mock "github.com/stretchr/testify/mock"
)

// CreateHandler is an autogenerated mock type for the CreateHandler type
type CreateHandler struct {
	mock.Mock
}

type CreateHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateHandler) EXPECT() *CreateHandler_Expecter {
	return &CreateHandler_Expecter{mock: &_m.Mock}
}

// GetCreateInput provides a mock function with no fields
func (_m *CreateHandler) GetCreateInput() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCreateInput")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// CreateHandler_GetCreateInput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCreateInput'
type CreateHandler_GetCreateInput_Call struct {
	*mock.Call
}

// GetCreateInput is a helper method to define mock.On call
func (_e *CreateHandler_Expecter) GetCreateInput() *CreateHandler_GetCreateInput_Call {
	return &CreateHandler_GetCreateInput_Call{Call: _e.mock.On("GetCreateInput")}
}

func (_c *CreateHandler_GetCreateInput_Call) Run(run func()) *CreateHandler_GetCreateInput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CreateHandler_GetCreateInput_Call) Return(_a0 interface{}) *CreateHandler_GetCreateInput_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CreateHandler_GetCreateInput_Call) RunAndReturn(run func() interface{}) *CreateHandler_GetCreateInput_Call {
	_c.Call.Return(run)
	return _c
}

// GetModel provides a mock function with no fields
func (_m *CreateHandler) GetModel() db_repo.ModelBased {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetModel")
	}

	var r0 db_repo.ModelBased
	if rf, ok := ret.Get(0).(func() db_repo.ModelBased); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(db_repo.ModelBased)
		}
	}

	return r0
}

// CreateHandler_GetModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModel'
type CreateHandler_GetModel_Call struct {
	*mock.Call
}

// GetModel is a helper method to define mock.On call
func (_e *CreateHandler_Expecter) GetModel() *CreateHandler_GetModel_Call {
	return &CreateHandler_GetModel_Call{Call: _e.mock.On("GetModel")}
}

func (_c *CreateHandler_GetModel_Call) Run(run func()) *CreateHandler_GetModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CreateHandler_GetModel_Call) Return(_a0 db_repo.ModelBased) *CreateHandler_GetModel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CreateHandler_GetModel_Call) RunAndReturn(run func() db_repo.ModelBased) *CreateHandler_GetModel_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepository provides a mock function with no fields
func (_m *CreateHandler) GetRepository() crud.Repository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRepository")
	}

	var r0 crud.Repository
	if rf, ok := ret.Get(0).(func() crud.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crud.Repository)
		}
	}

	return r0
}

// CreateHandler_GetRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepository'
type CreateHandler_GetRepository_Call struct {
	*mock.Call
}

// GetRepository is a helper method to define mock.On call
func (_e *CreateHandler_Expecter) GetRepository() *CreateHandler_GetRepository_Call {
	return &CreateHandler_GetRepository_Call{Call: _e.mock.On("GetRepository")}
}

func (_c *CreateHandler_GetRepository_Call) Run(run func()) *CreateHandler_GetRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CreateHandler_GetRepository_Call) Return(_a0 crud.Repository) *CreateHandler_GetRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CreateHandler_GetRepository_Call) RunAndReturn(run func() crud.Repository) *CreateHandler_GetRepository_Call {
	_c.Call.Return(run)
	return _c
}

// TransformCreate provides a mock function with given fields: ctx, input, model
func (_m *CreateHandler) TransformCreate(ctx context.Context, input interface{}, model db_repo.ModelBased) error {
	ret := _m.Called(ctx, input, model)

	if len(ret) == 0 {
		panic("no return value specified for TransformCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, db_repo.ModelBased) error); ok {
		r0 = rf(ctx, input, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateHandler_TransformCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransformCreate'
type CreateHandler_TransformCreate_Call struct {
	*mock.Call
}

// TransformCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - input interface{}
//   - model db_repo.ModelBased
func (_e *CreateHandler_Expecter) TransformCreate(ctx interface{}, input interface{}, model interface{}) *CreateHandler_TransformCreate_Call {
	return &CreateHandler_TransformCreate_Call{Call: _e.mock.On("TransformCreate", ctx, input, model)}
}

func (_c *CreateHandler_TransformCreate_Call) Run(run func(ctx context.Context, input interface{}, model db_repo.ModelBased)) *CreateHandler_TransformCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}), args[2].(db_repo.ModelBased))
	})
	return _c
}

func (_c *CreateHandler_TransformCreate_Call) Return(err error) *CreateHandler_TransformCreate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CreateHandler_TransformCreate_Call) RunAndReturn(run func(context.Context, interface{}, db_repo.ModelBased) error) *CreateHandler_TransformCreate_Call {
	_c.Call.Return(run)
	return _c
}

// TransformOutput provides a mock function with given fields: ctx, model, apiView
func (_m *CreateHandler) TransformOutput(ctx context.Context, model db_repo.ModelBased, apiView string) (interface{}, error) {
	ret := _m.Called(ctx, model, apiView)

	if len(ret) == 0 {
		panic("no return value specified for TransformOutput")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db_repo.ModelBased, string) (interface{}, error)); ok {
		return rf(ctx, model, apiView)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db_repo.ModelBased, string) interface{}); ok {
		r0 = rf(ctx, model, apiView)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db_repo.ModelBased, string) error); ok {
		r1 = rf(ctx, model, apiView)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateHandler_TransformOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransformOutput'
type CreateHandler_TransformOutput_Call struct {
	*mock.Call
}

// TransformOutput is a helper method to define mock.On call
//   - ctx context.Context
//   - model db_repo.ModelBased
//   - apiView string
func (_e *CreateHandler_Expecter) TransformOutput(ctx interface{}, model interface{}, apiView interface{}) *CreateHandler_TransformOutput_Call {
	return &CreateHandler_TransformOutput_Call{Call: _e.mock.On("TransformOutput", ctx, model, apiView)}
}

func (_c *CreateHandler_TransformOutput_Call) Run(run func(ctx context.Context, model db_repo.ModelBased, apiView string)) *CreateHandler_TransformOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db_repo.ModelBased), args[2].(string))
	})
	return _c
}

func (_c *CreateHandler_TransformOutput_Call) Return(output interface{}, err error) *CreateHandler_TransformOutput_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *CreateHandler_TransformOutput_Call) RunAndReturn(run func(context.Context, db_repo.ModelBased, string) (interface{}, error)) *CreateHandler_TransformOutput_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreateHandler creates a new instance of CreateHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateHandler {
	mock := &CreateHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
