// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.24.2
// source: message_builder_test.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstField    string                 `protobuf:"bytes,1,opt,name=first_field,json=firstField,proto3" json:"first_field,omitempty"`
	SecondField   uint32                 `protobuf:"varint,2,opt,name=second_field,json=secondField,proto3" json:"second_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_message_builder_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_builder_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_message_builder_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage) GetFirstField() string {
	if x != nil {
		return x.FirstField
	}
	return ""
}

func (x *TestMessage) GetSecondField() uint32 {
	if x != nil {
		return x.SecondField
	}
	return 0
}

var File_message_builder_test_proto protoreflect.FileDescriptor

const file_message_builder_test_proto_rawDesc = "" +
	"\n" +
	"\x1amessage_builder_test.proto\"Q\n" +
	"\vTestMessage\x12\x1f\n" +
	"\vfirst_field\x18\x01 \x01(\tR\n" +
	"firstField\x12!\n" +
	"\fsecond_field\x18\x02 \x01(\rR\vsecondFieldB\x11Z\x0fstream/testdatab\x06proto3"

var (
	file_message_builder_test_proto_rawDescOnce sync.Once
	file_message_builder_test_proto_rawDescData []byte
)

func file_message_builder_test_proto_rawDescGZIP() []byte {
	file_message_builder_test_proto_rawDescOnce.Do(func() {
		file_message_builder_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_builder_test_proto_rawDesc), len(file_message_builder_test_proto_rawDesc)))
	})
	return file_message_builder_test_proto_rawDescData
}

var file_message_builder_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_builder_test_proto_goTypes = []any{
	(*TestMessage)(nil), // 0: TestMessage
}
var file_message_builder_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_builder_test_proto_init() }
func file_message_builder_test_proto_init() {
	if File_message_builder_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_builder_test_proto_rawDesc), len(file_message_builder_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_builder_test_proto_goTypes,
		DependencyIndexes: file_message_builder_test_proto_depIdxs,
		MessageInfos:      file_message_builder_test_proto_msgTypes,
	}.Build()
	File_message_builder_test_proto = out.File
	file_message_builder_test_proto_goTypes = nil
	file_message_builder_test_proto_depIdxs = nil
}
