// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// ToEur provides a mock function with given fields: value, from
func (_m *Service) ToEur(value float64, from string) (float64, error) {
	ret := _m.Called(value, from)

	var r0 float64
	if rf, ok := ret.Get(0).(func(float64, string) float64); ok {
		r0 = rf(value, from)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(float64, string) error); ok {
		r1 = rf(value, from)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
