// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	resources "github.com/justtrackio/gosoline/pkg/resources"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetResources provides a mock function with given fields: filter
func (_m *Service) GetResources(filter resources.Filter) ([]string, error) {
	ret := _m.Called(filter)

	var r0 []string
	if rf, ok := ret.Get(0).(func(resources.Filter) []string); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(resources.Filter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
