// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	smpl "github.com/justtrackio/gosoline/pkg/smpl"
	mock "github.com/stretchr/testify/mock"
)

// Decider is an autogenerated mock type for the Decider type
type Decider struct {
	mock.Mock
}

type Decider_Expecter struct {
	mock *mock.Mock
}

func (_m *Decider) EXPECT() *Decider_Expecter {
	return &Decider_Expecter{mock: &_m.Mock}
}

// Decide provides a mock function with given fields: ctx, additionalStrategies
func (_m *Decider) Decide(ctx context.Context, additionalStrategies ...smpl.Strategy) (context.Context, bool, error) {
	_va := make([]interface{}, len(additionalStrategies))
	for _i := range additionalStrategies {
		_va[_i] = additionalStrategies[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Decide")
	}

	var r0 context.Context
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, ...smpl.Strategy) (context.Context, bool, error)); ok {
		return rf(ctx, additionalStrategies...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...smpl.Strategy) context.Context); ok {
		r0 = rf(ctx, additionalStrategies...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...smpl.Strategy) bool); ok {
		r1 = rf(ctx, additionalStrategies...)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, ...smpl.Strategy) error); ok {
		r2 = rf(ctx, additionalStrategies...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Decider_Decide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decide'
type Decider_Decide_Call struct {
	*mock.Call
}

// Decide is a helper method to define mock.On call
//   - ctx context.Context
//   - additionalStrategies ...smpl.Strategy
func (_e *Decider_Expecter) Decide(ctx interface{}, additionalStrategies ...interface{}) *Decider_Decide_Call {
	return &Decider_Decide_Call{Call: _e.mock.On("Decide",
		append([]interface{}{ctx}, additionalStrategies...)...)}
}

func (_c *Decider_Decide_Call) Run(run func(ctx context.Context, additionalStrategies ...smpl.Strategy)) *Decider_Decide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]smpl.Strategy, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(smpl.Strategy)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *Decider_Decide_Call) Return(_a0 context.Context, _a1 bool, _a2 error) *Decider_Decide_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Decider_Decide_Call) RunAndReturn(run func(context.Context, ...smpl.Strategy) (context.Context, bool, error)) *Decider_Decide_Call {
	_c.Call.Return(run)
	return _c
}

// NewDecider creates a new instance of Decider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Decider {
	mock := &Decider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
