app:
  env: dev
  name: stream-consumer
  tags:
    project: project
    family: family
    group: grp
  namespace: "{app.tags.project}.{app.env}.{app.tags.family}.{app.tags.group}"
  model_id:
    domain_pattern: "{app.tags.project}.{app.env}.{app.tags.family}.{app.tags.group}"

mdlsub:
  publishers:
    outputEvent: { output_type: sns, application: stream-consumer }

stream:
  consumer:
    uintConsumer:
      input: consumerInput

  input:
    consumerInput:
      type: sqs
      queue_id: inputEvent
