// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Authenticator is an autogenerated mock type for the Authenticator type
type Authenticator struct {
	mock.Mock
}

type Authenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *Authenticator) EXPECT() *Authenticator_Expecter {
	return &Authenticator_Expecter{mock: &_m.Mock}
}

// IsValid provides a mock function with given fields: ginCtx
func (_m *Authenticator) IsValid(ginCtx *gin.Context) (bool, error) {
	ret := _m.Called(ginCtx)

	if len(ret) == 0 {
		panic("no return value specified for IsValid")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (bool, error)); ok {
		return rf(ginCtx)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) bool); ok {
		r0 = rf(ginCtx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(ginCtx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Authenticator_IsValid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsValid'
type Authenticator_IsValid_Call struct {
	*mock.Call
}

// IsValid is a helper method to define mock.On call
//   - ginCtx *gin.Context
func (_e *Authenticator_Expecter) IsValid(ginCtx interface{}) *Authenticator_IsValid_Call {
	return &Authenticator_IsValid_Call{Call: _e.mock.On("IsValid", ginCtx)}
}

func (_c *Authenticator_IsValid_Call) Run(run func(ginCtx *gin.Context)) *Authenticator_IsValid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *Authenticator_IsValid_Call) Return(_a0 bool, _a1 error) *Authenticator_IsValid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Authenticator_IsValid_Call) RunAndReturn(run func(*gin.Context) (bool, error)) *Authenticator_IsValid_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthenticator creates a new instance of Authenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Authenticator {
	mock := &Authenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
