// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	context "context"

	stream "github.com/applike/gosoline/pkg/stream"
	mock "github.com/stretchr/testify/mock"
)

// PipelineCallback is an autogenerated mock type for the PipelineCallback type
type PipelineCallback struct {
	mock.Mock
}

// Process provides a mock function with given fields: ctx, messages
func (_m *PipelineCallback) Process(ctx context.Context, messages []*stream.Message) ([]*stream.Message, error) {
	ret := _m.Called(ctx, messages)

	var r0 []*stream.Message
	if rf, ok := ret.Get(0).(func(context.Context, []*stream.Message) []*stream.Message); ok {
		r0 = rf(ctx, messages)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*stream.Message)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []*stream.Message) error); ok {
		r1 = rf(ctx, messages)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
