// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RunnableConsumerCallback is an autogenerated mock type for the RunnableConsumerCallback type
type RunnableConsumerCallback[M interface{}] struct {
	mock.Mock
}

type RunnableConsumerCallback_Expecter[M interface{}] struct {
	mock *mock.Mock
}

func (_m *RunnableConsumerCallback[M]) EXPECT() *RunnableConsumerCallback_Expecter[M] {
	return &RunnableConsumerCallback_Expecter[M]{mock: &_m.Mock}
}

// Consume provides a mock function with given fields: ctx, model, attributes
func (_m *RunnableConsumerCallback[M]) Consume(ctx context.Context, model M, attributes map[string]string) (bool, error) {
	ret := _m.Called(ctx, model, attributes)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, M, map[string]string) (bool, error)); ok {
		return rf(ctx, model, attributes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, M, map[string]string) bool); ok {
		r0 = rf(ctx, model, attributes)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, M, map[string]string) error); ok {
		r1 = rf(ctx, model, attributes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RunnableConsumerCallback_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type RunnableConsumerCallback_Consume_Call[M interface{}] struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - model M
//   - attributes map[string]string
func (_e *RunnableConsumerCallback_Expecter[M]) Consume(ctx interface{}, model interface{}, attributes interface{}) *RunnableConsumerCallback_Consume_Call[M] {
	return &RunnableConsumerCallback_Consume_Call[M]{Call: _e.mock.On("Consume", ctx, model, attributes)}
}

func (_c *RunnableConsumerCallback_Consume_Call[M]) Run(run func(ctx context.Context, model M, attributes map[string]string)) *RunnableConsumerCallback_Consume_Call[M] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(M), args[2].(map[string]string))
	})
	return _c
}

func (_c *RunnableConsumerCallback_Consume_Call[M]) Return(_a0 bool, _a1 error) *RunnableConsumerCallback_Consume_Call[M] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RunnableConsumerCallback_Consume_Call[M]) RunAndReturn(run func(context.Context, M, map[string]string) (bool, error)) *RunnableConsumerCallback_Consume_Call[M] {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: ctx
func (_m *RunnableConsumerCallback[M]) Run(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RunnableConsumerCallback_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type RunnableConsumerCallback_Run_Call[M interface{}] struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RunnableConsumerCallback_Expecter[M]) Run(ctx interface{}) *RunnableConsumerCallback_Run_Call[M] {
	return &RunnableConsumerCallback_Run_Call[M]{Call: _e.mock.On("Run", ctx)}
}

func (_c *RunnableConsumerCallback_Run_Call[M]) Run(run func(ctx context.Context)) *RunnableConsumerCallback_Run_Call[M] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RunnableConsumerCallback_Run_Call[M]) Return(_a0 error) *RunnableConsumerCallback_Run_Call[M] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RunnableConsumerCallback_Run_Call[M]) RunAndReturn(run func(context.Context) error) *RunnableConsumerCallback_Run_Call[M] {
	_c.Call.Return(run)
	return _c
}

// NewRunnableConsumerCallback creates a new instance of RunnableConsumerCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRunnableConsumerCallback[M interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *RunnableConsumerCallback[M] {
	mock := &RunnableConsumerCallback[M]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
