// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RunnableBatchConsumerCallback is an autogenerated mock type for the RunnableBatchConsumerCallback type
type RunnableBatchConsumerCallback[M interface{}] struct {
	mock.Mock
}

type RunnableBatchConsumerCallback_Expecter[M interface{}] struct {
	mock *mock.Mock
}

func (_m *RunnableBatchConsumerCallback[M]) EXPECT() *RunnableBatchConsumerCallback_Expecter[M] {
	return &RunnableBatchConsumerCallback_Expecter[M]{mock: &_m.Mock}
}

// Consume provides a mock function with given fields: _a0, _a1, _a2
func (_m *RunnableBatchConsumerCallback[M]) Consume(_a0 context.Context, _a1 []M, _a2 []map[string]string) ([]bool, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 []bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []M, []map[string]string) ([]bool, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []M, []map[string]string) []bool); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []M, []map[string]string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RunnableBatchConsumerCallback_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type RunnableBatchConsumerCallback_Consume_Call[M interface{}] struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []M
//   - _a2 []map[string]string
func (_e *RunnableBatchConsumerCallback_Expecter[M]) Consume(_a0 interface{}, _a1 interface{}, _a2 interface{}) *RunnableBatchConsumerCallback_Consume_Call[M] {
	return &RunnableBatchConsumerCallback_Consume_Call[M]{Call: _e.mock.On("Consume", _a0, _a1, _a2)}
}

func (_c *RunnableBatchConsumerCallback_Consume_Call[M]) Run(run func(_a0 context.Context, _a1 []M, _a2 []map[string]string)) *RunnableBatchConsumerCallback_Consume_Call[M] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]M), args[2].([]map[string]string))
	})
	return _c
}

func (_c *RunnableBatchConsumerCallback_Consume_Call[M]) Return(_a0 []bool, _a1 error) *RunnableBatchConsumerCallback_Consume_Call[M] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RunnableBatchConsumerCallback_Consume_Call[M]) RunAndReturn(run func(context.Context, []M, []map[string]string) ([]bool, error)) *RunnableBatchConsumerCallback_Consume_Call[M] {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: ctx
func (_m *RunnableBatchConsumerCallback[M]) Run(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RunnableBatchConsumerCallback_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type RunnableBatchConsumerCallback_Run_Call[M interface{}] struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RunnableBatchConsumerCallback_Expecter[M]) Run(ctx interface{}) *RunnableBatchConsumerCallback_Run_Call[M] {
	return &RunnableBatchConsumerCallback_Run_Call[M]{Call: _e.mock.On("Run", ctx)}
}

func (_c *RunnableBatchConsumerCallback_Run_Call[M]) Run(run func(ctx context.Context)) *RunnableBatchConsumerCallback_Run_Call[M] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RunnableBatchConsumerCallback_Run_Call[M]) Return(_a0 error) *RunnableBatchConsumerCallback_Run_Call[M] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RunnableBatchConsumerCallback_Run_Call[M]) RunAndReturn(run func(context.Context) error) *RunnableBatchConsumerCallback_Run_Call[M] {
	_c.Call.Return(run)
	return _c
}

// NewRunnableBatchConsumerCallback creates a new instance of RunnableBatchConsumerCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRunnableBatchConsumerCallback[M interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *RunnableBatchConsumerCallback[M] {
	mock := &RunnableBatchConsumerCallback[M]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
