// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	stream "github.com/justtrackio/gosoline/pkg/stream"
	mock "github.com/stretchr/testify/mock"
)

// SizeRestrictedOutput is an autogenerated mock type for the SizeRestrictedOutput type
type SizeRestrictedOutput struct {
	mock.Mock
}

type SizeRestrictedOutput_Expecter struct {
	mock *mock.Mock
}

func (_m *SizeRestrictedOutput) EXPECT() *SizeRestrictedOutput_Expecter {
	return &SizeRestrictedOutput_Expecter{mock: &_m.Mock}
}

// GetMaxBatchSize provides a mock function with no fields
func (_m *SizeRestrictedOutput) GetMaxBatchSize() *int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMaxBatchSize")
	}

	var r0 *int
	if rf, ok := ret.Get(0).(func() *int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}

	return r0
}

// SizeRestrictedOutput_GetMaxBatchSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxBatchSize'
type SizeRestrictedOutput_GetMaxBatchSize_Call struct {
	*mock.Call
}

// GetMaxBatchSize is a helper method to define mock.On call
func (_e *SizeRestrictedOutput_Expecter) GetMaxBatchSize() *SizeRestrictedOutput_GetMaxBatchSize_Call {
	return &SizeRestrictedOutput_GetMaxBatchSize_Call{Call: _e.mock.On("GetMaxBatchSize")}
}

func (_c *SizeRestrictedOutput_GetMaxBatchSize_Call) Run(run func()) *SizeRestrictedOutput_GetMaxBatchSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SizeRestrictedOutput_GetMaxBatchSize_Call) Return(_a0 *int) *SizeRestrictedOutput_GetMaxBatchSize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SizeRestrictedOutput_GetMaxBatchSize_Call) RunAndReturn(run func() *int) *SizeRestrictedOutput_GetMaxBatchSize_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaxMessageSize provides a mock function with no fields
func (_m *SizeRestrictedOutput) GetMaxMessageSize() *int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMaxMessageSize")
	}

	var r0 *int
	if rf, ok := ret.Get(0).(func() *int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}

	return r0
}

// SizeRestrictedOutput_GetMaxMessageSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxMessageSize'
type SizeRestrictedOutput_GetMaxMessageSize_Call struct {
	*mock.Call
}

// GetMaxMessageSize is a helper method to define mock.On call
func (_e *SizeRestrictedOutput_Expecter) GetMaxMessageSize() *SizeRestrictedOutput_GetMaxMessageSize_Call {
	return &SizeRestrictedOutput_GetMaxMessageSize_Call{Call: _e.mock.On("GetMaxMessageSize")}
}

func (_c *SizeRestrictedOutput_GetMaxMessageSize_Call) Run(run func()) *SizeRestrictedOutput_GetMaxMessageSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SizeRestrictedOutput_GetMaxMessageSize_Call) Return(_a0 *int) *SizeRestrictedOutput_GetMaxMessageSize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SizeRestrictedOutput_GetMaxMessageSize_Call) RunAndReturn(run func() *int) *SizeRestrictedOutput_GetMaxMessageSize_Call {
	_c.Call.Return(run)
	return _c
}

// ProvidesCompression provides a mock function with no fields
func (_m *SizeRestrictedOutput) ProvidesCompression() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProvidesCompression")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SizeRestrictedOutput_ProvidesCompression_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProvidesCompression'
type SizeRestrictedOutput_ProvidesCompression_Call struct {
	*mock.Call
}

// ProvidesCompression is a helper method to define mock.On call
func (_e *SizeRestrictedOutput_Expecter) ProvidesCompression() *SizeRestrictedOutput_ProvidesCompression_Call {
	return &SizeRestrictedOutput_ProvidesCompression_Call{Call: _e.mock.On("ProvidesCompression")}
}

func (_c *SizeRestrictedOutput_ProvidesCompression_Call) Run(run func()) *SizeRestrictedOutput_ProvidesCompression_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SizeRestrictedOutput_ProvidesCompression_Call) Return(_a0 bool) *SizeRestrictedOutput_ProvidesCompression_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SizeRestrictedOutput_ProvidesCompression_Call) RunAndReturn(run func() bool) *SizeRestrictedOutput_ProvidesCompression_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsAggregation provides a mock function with no fields
func (_m *SizeRestrictedOutput) SupportsAggregation() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsAggregation")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SizeRestrictedOutput_SupportsAggregation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsAggregation'
type SizeRestrictedOutput_SupportsAggregation_Call struct {
	*mock.Call
}

// SupportsAggregation is a helper method to define mock.On call
func (_e *SizeRestrictedOutput_Expecter) SupportsAggregation() *SizeRestrictedOutput_SupportsAggregation_Call {
	return &SizeRestrictedOutput_SupportsAggregation_Call{Call: _e.mock.On("SupportsAggregation")}
}

func (_c *SizeRestrictedOutput_SupportsAggregation_Call) Run(run func()) *SizeRestrictedOutput_SupportsAggregation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SizeRestrictedOutput_SupportsAggregation_Call) Return(_a0 bool) *SizeRestrictedOutput_SupportsAggregation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SizeRestrictedOutput_SupportsAggregation_Call) RunAndReturn(run func() bool) *SizeRestrictedOutput_SupportsAggregation_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: ctx, batch
func (_m *SizeRestrictedOutput) Write(ctx context.Context, batch []stream.WritableMessage) error {
	ret := _m.Called(ctx, batch)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []stream.WritableMessage) error); ok {
		r0 = rf(ctx, batch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SizeRestrictedOutput_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type SizeRestrictedOutput_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - batch []stream.WritableMessage
func (_e *SizeRestrictedOutput_Expecter) Write(ctx interface{}, batch interface{}) *SizeRestrictedOutput_Write_Call {
	return &SizeRestrictedOutput_Write_Call{Call: _e.mock.On("Write", ctx, batch)}
}

func (_c *SizeRestrictedOutput_Write_Call) Run(run func(ctx context.Context, batch []stream.WritableMessage)) *SizeRestrictedOutput_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]stream.WritableMessage))
	})
	return _c
}

func (_c *SizeRestrictedOutput_Write_Call) Return(_a0 error) *SizeRestrictedOutput_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SizeRestrictedOutput_Write_Call) RunAndReturn(run func(context.Context, []stream.WritableMessage) error) *SizeRestrictedOutput_Write_Call {
	_c.Call.Return(run)
	return _c
}

// WriteOne provides a mock function with given fields: ctx, msg
func (_m *SizeRestrictedOutput) WriteOne(ctx context.Context, msg stream.WritableMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for WriteOne")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, stream.WritableMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SizeRestrictedOutput_WriteOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteOne'
type SizeRestrictedOutput_WriteOne_Call struct {
	*mock.Call
}

// WriteOne is a helper method to define mock.On call
//   - ctx context.Context
//   - msg stream.WritableMessage
func (_e *SizeRestrictedOutput_Expecter) WriteOne(ctx interface{}, msg interface{}) *SizeRestrictedOutput_WriteOne_Call {
	return &SizeRestrictedOutput_WriteOne_Call{Call: _e.mock.On("WriteOne", ctx, msg)}
}

func (_c *SizeRestrictedOutput_WriteOne_Call) Run(run func(ctx context.Context, msg stream.WritableMessage)) *SizeRestrictedOutput_WriteOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(stream.WritableMessage))
	})
	return _c
}

func (_c *SizeRestrictedOutput_WriteOne_Call) Return(_a0 error) *SizeRestrictedOutput_WriteOne_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SizeRestrictedOutput_WriteOne_Call) RunAndReturn(run func(context.Context, stream.WritableMessage) error) *SizeRestrictedOutput_WriteOne_Call {
	_c.Call.Return(run)
	return _c
}

// NewSizeRestrictedOutput creates a new instance of SizeRestrictedOutput. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSizeRestrictedOutput(t interface {
	mock.TestingT
	Cleanup(func())
}) *SizeRestrictedOutput {
	mock := &SizeRestrictedOutput{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
