// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TypedConsumerCallback is an autogenerated mock type for the TypedConsumerCallback type
type TypedConsumerCallback[M interface{}] struct {
	mock.Mock
}

type TypedConsumerCallback_Expecter[M interface{}] struct {
	mock *mock.Mock
}

func (_m *TypedConsumerCallback[M]) EXPECT() *TypedConsumerCallback_Expecter[M] {
	return &TypedConsumerCallback_Expecter[M]{mock: &_m.Mock}
}

// Consume provides a mock function with given fields: ctx, model, attributes
func (_m *TypedConsumerCallback[M]) Consume(ctx context.Context, model M, attributes map[string]string) (bool, error) {
	ret := _m.Called(ctx, model, attributes)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, M, map[string]string) (bool, error)); ok {
		return rf(ctx, model, attributes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, M, map[string]string) bool); ok {
		r0 = rf(ctx, model, attributes)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, M, map[string]string) error); ok {
		r1 = rf(ctx, model, attributes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TypedConsumerCallback_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type TypedConsumerCallback_Consume_Call[M interface{}] struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - model M
//   - attributes map[string]string
func (_e *TypedConsumerCallback_Expecter[M]) Consume(ctx interface{}, model interface{}, attributes interface{}) *TypedConsumerCallback_Consume_Call[M] {
	return &TypedConsumerCallback_Consume_Call[M]{Call: _e.mock.On("Consume", ctx, model, attributes)}
}

func (_c *TypedConsumerCallback_Consume_Call[M]) Run(run func(ctx context.Context, model M, attributes map[string]string)) *TypedConsumerCallback_Consume_Call[M] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(M), args[2].(map[string]string))
	})
	return _c
}

func (_c *TypedConsumerCallback_Consume_Call[M]) Return(_a0 bool, _a1 error) *TypedConsumerCallback_Consume_Call[M] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TypedConsumerCallback_Consume_Call[M]) RunAndReturn(run func(context.Context, M, map[string]string) (bool, error)) *TypedConsumerCallback_Consume_Call[M] {
	_c.Call.Return(run)
	return _c
}

// NewTypedConsumerCallback creates a new instance of TypedConsumerCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTypedConsumerCallback[M interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *TypedConsumerCallback[M] {
	mock := &TypedConsumerCallback[M]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
