env: test

app_project: gosoline
app_family: stream-example
app_name: batch-publisher-example

mdlsub:
  publishers:
    examplePublisher: { output_type: inMemory }

stream:
  producer:
    publisher-examplePublisher:
      daemon:
        enabled: true
        aggregation_size: 5
