// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StagedModule is an autogenerated mock type for the StagedModule type
type StagedModule struct {
	mock.Mock
}

// GetStage provides a mock function with given fields:
func (_m *StagedModule) GetStage() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewStagedModule interface {
	mock.TestingT
	Cleanup(func())
}

// NewStagedModule creates a new instance of StagedModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStagedModule(t mockConstructorTestingTNewStagedModule) *StagedModule {
	mock := &StagedModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
