// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	blob "github.com/justtrackio/gosoline/pkg/blob"

	mock "github.com/stretchr/testify/mock"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

type Reader_Expecter struct {
	mock *mock.Mock
}

func (_m *Reader) EXPECT() *Reader_Expecter {
	return &Reader_Expecter{mock: &_m.Mock}
}

// Chan provides a mock function with given fields: ctx
func (_m *Reader) Chan(ctx context.Context) (<-chan blob.Object, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Chan")
	}

	var r0 <-chan blob.Object
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (<-chan blob.Object, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) <-chan blob.Object); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan blob.Object)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reader_Chan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chan'
type Reader_Chan_Call struct {
	*mock.Call
}

// Chan is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Reader_Expecter) Chan(ctx interface{}) *Reader_Chan_Call {
	return &Reader_Chan_Call{Call: _e.mock.On("Chan", ctx)}
}

func (_c *Reader_Chan_Call) Run(run func(ctx context.Context)) *Reader_Chan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Reader_Chan_Call) Return(_a0 <-chan blob.Object, _a1 error) *Reader_Chan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Reader_Chan_Call) RunAndReturn(run func(context.Context) (<-chan blob.Object, error)) *Reader_Chan_Call {
	_c.Call.Return(run)
	return _c
}

// NewReader creates a new instance of Reader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reader {
	mock := &Reader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
