env: dev

app_project: project
app_family: family
app_group: grp
app_name: name

httpserver:
  default:
    port: 8088
    mode: debug
    timeout:
      read: 5s
      write: 5s
      idle: 5s

task_runner:
  enabled: true
