// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	apiserver "github.com/justtrackio/gosoline/pkg/apiserver"

	mock "github.com/stretchr/testify/mock"
)

// HandlerWithoutInput is an autogenerated mock type for the HandlerWithoutInput type
type HandlerWithoutInput struct {
	mock.Mock
}

// Handle provides a mock function with given fields: requestContext, request
func (_m *HandlerWithoutInput) Handle(requestContext context.Context, request *apiserver.Request) (*apiserver.Response, error) {
	ret := _m.Called(requestContext, request)

	var r0 *apiserver.Response
	if rf, ok := ret.Get(0).(func(context.Context, *apiserver.Request) *apiserver.Response); ok {
		r0 = rf(requestContext, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiserver.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *apiserver.Request) error); ok {
		r1 = rf(requestContext, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewHandlerWithoutInput interface {
	mock.TestingT
	Cleanup(func())
}

// NewHandlerWithoutInput creates a new instance of HandlerWithoutInput. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHandlerWithoutInput(t mockConstructorTestingTNewHandlerWithoutInput) *HandlerWithoutInput {
	mock := &HandlerWithoutInput{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
