// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	kgo "github.com/twmb/franz-go/pkg/kgo"
)

// PartitionClient is an autogenerated mock type for the partitionClient type
type PartitionClient struct {
	mock.Mock
}

type PartitionClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PartitionClient) EXPECT() *PartitionClient_Expecter {
	return &PartitionClient_Expecter{mock: &_m.Mock}
}

// CommitRecords provides a mock function with given fields: ctx, records
func (_m *PartitionClient) CommitRecords(ctx context.Context, records ...*kgo.Record) error {
	_va := make([]interface{}, len(records))
	for _i := range records {
		_va[_i] = records[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CommitRecords")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...*kgo.Record) error); ok {
		r0 = rf(ctx, records...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartitionClient_CommitRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitRecords'
type PartitionClient_CommitRecords_Call struct {
	*mock.Call
}

// CommitRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - records ...*kgo.Record
func (_e *PartitionClient_Expecter) CommitRecords(ctx interface{}, records ...interface{}) *PartitionClient_CommitRecords_Call {
	return &PartitionClient_CommitRecords_Call{Call: _e.mock.On("CommitRecords",
		append([]interface{}{ctx}, records...)...)}
}

func (_c *PartitionClient_CommitRecords_Call) Run(run func(ctx context.Context, records ...*kgo.Record)) *PartitionClient_CommitRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*kgo.Record, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(*kgo.Record)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *PartitionClient_CommitRecords_Call) Return(_a0 error) *PartitionClient_CommitRecords_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartitionClient_CommitRecords_Call) RunAndReturn(run func(context.Context, ...*kgo.Record) error) *PartitionClient_CommitRecords_Call {
	_c.Call.Return(run)
	return _c
}

// PauseFetchPartitions provides a mock function with given fields: topicPartitions
func (_m *PartitionClient) PauseFetchPartitions(topicPartitions map[string][]int32) map[string][]int32 {
	ret := _m.Called(topicPartitions)

	if len(ret) == 0 {
		panic("no return value specified for PauseFetchPartitions")
	}

	var r0 map[string][]int32
	if rf, ok := ret.Get(0).(func(map[string][]int32) map[string][]int32); ok {
		r0 = rf(topicPartitions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]int32)
		}
	}

	return r0
}

// PartitionClient_PauseFetchPartitions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseFetchPartitions'
type PartitionClient_PauseFetchPartitions_Call struct {
	*mock.Call
}

// PauseFetchPartitions is a helper method to define mock.On call
//   - topicPartitions map[string][]int32
func (_e *PartitionClient_Expecter) PauseFetchPartitions(topicPartitions interface{}) *PartitionClient_PauseFetchPartitions_Call {
	return &PartitionClient_PauseFetchPartitions_Call{Call: _e.mock.On("PauseFetchPartitions", topicPartitions)}
}

func (_c *PartitionClient_PauseFetchPartitions_Call) Run(run func(topicPartitions map[string][]int32)) *PartitionClient_PauseFetchPartitions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string][]int32))
	})
	return _c
}

func (_c *PartitionClient_PauseFetchPartitions_Call) Return(_a0 map[string][]int32) *PartitionClient_PauseFetchPartitions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartitionClient_PauseFetchPartitions_Call) RunAndReturn(run func(map[string][]int32) map[string][]int32) *PartitionClient_PauseFetchPartitions_Call {
	_c.Call.Return(run)
	return _c
}

// ResumeFetchPartitions provides a mock function with given fields: topicPartitions
func (_m *PartitionClient) ResumeFetchPartitions(topicPartitions map[string][]int32) {
	_m.Called(topicPartitions)
}

// PartitionClient_ResumeFetchPartitions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResumeFetchPartitions'
type PartitionClient_ResumeFetchPartitions_Call struct {
	*mock.Call
}

// ResumeFetchPartitions is a helper method to define mock.On call
//   - topicPartitions map[string][]int32
func (_e *PartitionClient_Expecter) ResumeFetchPartitions(topicPartitions interface{}) *PartitionClient_ResumeFetchPartitions_Call {
	return &PartitionClient_ResumeFetchPartitions_Call{Call: _e.mock.On("ResumeFetchPartitions", topicPartitions)}
}

func (_c *PartitionClient_ResumeFetchPartitions_Call) Run(run func(topicPartitions map[string][]int32)) *PartitionClient_ResumeFetchPartitions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string][]int32))
	})
	return _c
}

func (_c *PartitionClient_ResumeFetchPartitions_Call) Return() *PartitionClient_ResumeFetchPartitions_Call {
	_c.Call.Return()
	return _c
}

func (_c *PartitionClient_ResumeFetchPartitions_Call) RunAndReturn(run func(map[string][]int32)) *PartitionClient_ResumeFetchPartitions_Call {
	_c.Run(run)
	return _c
}

// NewPartitionClient creates a new instance of PartitionClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartitionClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartitionClient {
	mock := &PartitionClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
