app:
  env: dev
  name: exchange
  tags:
    project: gosoline
    family: example
    group: money

xchange

httpserver:
  default:
    port: 8080

kvstore:
  currency:
    type: chain
    in_memory:
      max_size: 500000
    application: money-exchange
    elements: [inMemory]
    ttl: 30m
