name: "Update .md files"

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout on the lastest commit
        uses: actions/checkout@v2
        with:
          repository: ''
          ref: ''

      - name: setup golang
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14.0'

      - name: running embedmed
        run: |
          go get github.com/campoy/embedmd
          cd docs
          embedmd -w $(find *.md)
