name: "Update .md files"

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout on the lastest commit
        uses: actions/checkout@v2
        with:
          repository: ''
          ref: ''

      - name: setup golang
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.17.0'

      - name: "running embedded"
        run: |
          go get github.com/campoy/embedmd
          embedmd -w README.md

      - name: auto-commit action
        uses: docker://cdssnc/touched-github-action:latest
        with:
          args: auto-commit/**
      - name: build auto-commit
        uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
        with:
          args: build -t cdssnc/auto-commit-github-action ./auto-commit
      - name: push auto-commit
        uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
        with:
          args: push cdssnc/auto-commit-github-action
