name: GitHub Actions Demo

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: install embedmd
        run: |
          go get github.com/campoy/embedmd

      - name: list all .md files in the repository
        run: |
          find ${{ github.workspace }} -type f | grep *.md | cut -c 2-

