name: "Update .md files"

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.17.0'

      - name: go version
        run: |
          go version

      - name: install embedmd
        run: |
          go get github.com/campoy/embedmd

      - name: list all .md files in the repository
        run: |
          find ${{ github.workspace }} -type f | grep *.md | cut -c 2-

      - name: run embedmd
        run: |
          embedmd -d ${{ github.workspace }}/README.md
