// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	cloud "github.com/justtrackio/gosoline/pkg/cloud"
	mock "github.com/stretchr/testify/mock"
)

// SsmClient is an autogenerated mock type for the SsmClient type
type SsmClient struct {
	mock.Mock
}

// GetParameter provides a mock function with given fields: _a0
func (_m *SsmClient) GetParameter(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetParameters provides a mock function with given fields: _a0
func (_m *SsmClient) GetParameters(_a0 string) (cloud.SsmParameters, error) {
	ret := _m.Called(_a0)

	var r0 cloud.SsmParameters
	if rf, ok := ret.Get(0).(func(string) cloud.SsmParameters); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cloud.SsmParameters)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
