env: test

app_project: gosoline
app_family: stream-example
app_name: consumer-example

stream:
  consumer:
    default:
      input: exampleInput
      runner_count: 1
  input:
    exampleInput:
      type: inMemory
      size: 1
